### PR TITLE
Fix #143

### LINKED ISSUE #143: Async parsing accepts weird stuff
Noted by @BenFradet [here](https://github.com/circe/circe-fs2/pull/47). Might be #135?

```scala
scala> import org.typelevel.jawn.{AsyncParser, NullFacade}
import org.typelevel.jawn.{AsyncParser, NullFacade}

scala> val p = AsyncParser[Unit](AsyncParser.UnwrapArray)
p: org.typelevel.jawn.AsyncParser[Unit] = org.typelevel.jawn.AsyncParser@3b623061

scala> p.absorb("}")(NullFacade)
res0: Either[org.typelevel.jawn.ParseException,Seq[Unit]] = Right(ArrayBuffer())
```
In 0.13.0 you get an error:
```scala
scala> p.absorb("}")(NullFacade)
res0: Either[jawn.ParseException,Seq[Unit]] = Left(jawn.ParseException: expected json value got } (line 1, column 1))
```
(Both 0.13.0 and 0.14.0 fail with the same error on `finish`.)

### PR DESCRIPTION
**Pull request by travisbrown**
This is a funny one. The problem is that the new error message stuff from #129 calls `at(i, j)` with out-of-bounds arguments on `AsyncParser`, which throws an `AsyncException` instead of a `ParseException`, which means the `absorb` call isn't treated as a failure.

My feeling is that we're going to keep seeing problems introduced by #129 for a while, starting with #142, which I'm hoping to get to next.

r? @BenFradet @non

### CODE REVIEW

**Comment by BenFradet** [comment]
Nice, thanks for digging into it!

**Comment by travisbrown** [comment]
Note that this means that `Parser.parseFromString("}x")(NullFacade)` fails with the following:

```scala
ParseException: expected json value got '}...' (line 1, column 1)
```
…instead of the current:
```scala
ParseException: expected json value got '}x' (line 1, column 1)
```
…which seems reasonable to me, but we could alternatively fix this by making sure `die` doesn't leak `AsyncException`s.

**Comment by rossabaker** [comment]
Some more things that return `Right` on `absorb` even though they're already bad:

* `fälse`
* `nüll`
* `trüe`
* `0x`
* `0.x`
* `0ex`
* `[1; 2]`
* `{"a"; 1}`
* `{1: 2}`
* I'm pretty sure a Unicode one, but I couldn't make it die in the right place

This fix works, but maybe it's worth exploring that alternative idea with the leaking `AsyncException`s to handle more of these.

**Comment by travisbrown** [comment]
@rossabaker Nice. And agreed. I'm happy to take a stab at it but it might be a couple of days, so if someone else wants to deal with it sooner I'm happy to review.

**Comment by travisbrown** [comment]
Just pushed a fix that makes sure `die` doesn't throw `AsyncException`.

File: parser/src/main/scala/jawn/Parser.scala [hunk 1]
```diff
@@ -90,6 +90,23 @@ abstract class Parser[J] {
...
+   * This method is necessary because `at(i, j)` may fail with an exception even
+   * when `atEof(i, j)` returns false (see #143 for an example). This method is
+   * a workaround; it is not optimized or robust against invalid input and
+   * should not be used outside of the context of `die`.
+   */
+  private[this] def safeAt(i: Int, j: Int): CharSequence =
+    if (j <= i) "" else {
+      try at(i, j) catch {
+        case _: Exception =>
+          safeAt(i, j - 1)
```
Comment (rossabaker) [inline parser/src/main/scala/jawn/Parser.scala]: `j-i` is at most `ErrorContext` (which is 6), right?  Just wondering about catching and throwing absurd numbers of exceptions as it walks back, but I won't lose sleep over up to 6.  And I think it's `@tailrec`, though I didn't ask scalac.

Comment (travisbrown) [reply parser/src/main/scala/jawn/Parser.scala]: In theory you could pass some ridiculously large context to `die`, but it's protected, so I'm not too worried about that. Also except in the (kind of weird) `AsyncParser` usage the `at` call in `safeAt` will never throw exceptions at all, since `atEof` has been checked.

(It is `@tailrec`, by the way, so I went ahead and added it.)
